services:
  - type: web
    name: moneyiq-personal-api
    runtime: docker
    dockerfilePath: ./backend/springboot-api/Dockerfile
    dockerContext: ./backend/springboot-api
    plan: free
    region: oregon
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        fromDatabase:
          name: moneyiq-personal-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: moneyiq-personal-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: moneyiq-personal-db
          property: password
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"

databases:
  - name: moneyiq-personal-db
    plan: free
    databaseName: moneyiqpersonal
    user: moneyiq_user
